### ISSUE TITLE
Getting this error when the scanning in Github

### ISSUE THREAD

**Issue by Balakrishna-Rao** [mitchspano/sfdx-scan-pull-request#82]
Error description.

Scan is not working and the comments are not added to github

 ErrorCaptureStackTrace(err);
    ^

<ref *1> Error: spawnSync /bin/sh ENOBUFS
    at Object.spawnSync (node:internal/child_process:1119:20)
    at spawnSync (node:child_process:847:24)
    at execSync (node:child_process:927:15)
    at /home/runner/_work/_actions/mitchspano/sfdx-scan-pull-request/v0.1.15/dist/index.js:1:1520
    at Generator.next (<anonymous>)
    at /home/runner/_work/_actions/mitchspano/sfdx-scan-pull-request/v0.1.15/dist/index.js:1:1059
    at new Promise (<anonymous>)
    at o (/home/runner/_work/_actions/mitchspano/sfdx-scan-pull-request/v0.1.15/dist/index.js:1:806)
    at getDiffInPullRequest (/home/runner/_work/_actions/mitchspano/sfdx-scan-pull-request/v0.1.15/dist/index.js:1:1382)
    at /home/runner/_work/_actions/mitchspano/sfdx-scan-pull-request/v0.1.15/dist/index.js:1:5656 {
  errno: -105,
  code: 'ENOBUFS',
  syscall: 'spawnSync /bin/sh',
  path: '/bin/sh',
  spawnargs: [
    '-c',
    'git remote add -f destination
 ],
  error: [Circular *1],
  status: null,
  signal: 'SIGTERM',
  output: [
    null,
    Buffer(21) [Uint8Array] [
       85, 112, 100,  97, 116, 105,
      110, 103,  32, 100, 101, 115,
      116, 105, 110,  97, 116, 105,
      111, 110,  10
    ],
    Buffer(1048576) [Uint8Array] [
       70, 114, 111, 109,  32, 104, 116, 116, 112, 115,  58,  47,
       47, 103, 105, 116, 104, 117,  98,  46,  99, 111, 109,  47,
       69, 108, 105, 115,  97,  79,  70,  47,  79, 110, 108, 105,
      110, 101,  70, 105, 114, 115, 116,  80, 114, 111, 106, 101,
       99, 116,  10,  32,  42,  32,  91, 110, 101, 119,  32,  98,
      114,  97, 110,  99, 104,  93,  32,  32,  32,  32,  32,  32,
       32,  32,  32,  32,  32,  32,  68,  67,  84,  32,  32,  32,
       32,  32,  32,  32,  32,  32,  32,  32,  32,  32,  32,  32,
       32,  32,  32,  32,
      ... 1048476 more items
    ]
  ],
  pid: 644,
  stdout: Buffer(21) [Uint8Array] [
     85, 112, 100,  97, 116, 105,
    110, 103,  32, 100, 101, 115,
    116, 105, 110,  97, 116, 105,
    111, 110,  10
  ],
  stderr: Buffer(1048576) [Uint8Array] [
     70, 114, 111, 109,  32, 104, 116, 116, 112, 115,  58,  47,
     47, 103, 105, 116, 104, 117,  98,  46,  99, 111, 109,  47,
     69, 108, 105, 115,  97,  79,  70,  47,  79, 110, 108, 105,
    110, 101,  70, 105, 114, 115, 116,  80, 114, 111, 106, 101,
     99, 116,  10,  32,  42,  32,  91, 110, 101, 119,  32,  98,
    114,  97, 110,  99, 104,  93,  32,  32,  32,  32,  32,  32,
     32,  32,  32,  32,  32,  32,  68,  67,  84,  32,  32,  32,
     32,  32,  32,  32,  32,  32,  32,  32,  32,  32,  32,  32,
     32,  32,  32,  32,
    ... 1048476 more items
  ]

**Comment by mitchspano** [comment]
Can you please share your `.yml` file for the action?

**Comment by Balakrishna-Rao** [comment]
Hi Mitch,

here is the yml file, I am using in the github


name: Run Scanner

on:
   pull_request:
       branches:
            - master
            - Dev
       types: [opened, reopened, synchronize]  
permissions: write-all
jobs:
  scan-files:
    runs-on: normal
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install SFDX CLI and Scanner
        run: |
          npm install sfdx-cli -g
          sfdx plugins:install @salesforce/sfdx-scanner
      - name: Apex static analysis
        uses: mitchspano/sfdx-scan-pull-request@v0.1.15
        with:
          pmdconfig: .github/workflows/pmd-ruleset.xml
          severity-threshold: 4
          engine: pmd
          report-mode: comments
          strictly-enforced-rules: '[{ "engine": "pmd", "category": "Performance", "rule": "AvoidDebugStatements" }]'
          target: tests
          eslintconfig: .eslintrc.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
